export const GET_ABOUT_US_RECORD_REQUEST = "GET_ABOUT_US_RECORD_REQUEST";
export const GET_ABOUT_US_RECORD_SUCCESS = "GET_ABOUT_US_RECORD_SUCCESS";
export const GET_ABOUT_US_RECORD_FAILURE = "GET_ABOUT_US_RECORD_FAILURE";