export const GET_CONTACT_DATA_REQUEST = "GET_CONTACT_DATA_REQUEST";
export const GET_CONTACT_DATA_SUCCESS = "GET_CONTACT_DATA_SUCCESS";
export const GET_CONTACT_DATA_FAILURE = "GET_CONTACT_DATA_FAILURE";