export const GET_GOOGLE_REVIEW_REQUEST = "GET_GOOGLE_REVIEW_REQUEST";
export const GET_GOOGLE_REVIEW_SUCCESS = "GET_GOOGLE_REVIEW_SUCCESS";
export const GET_GOOGLE_REVIEW_FAILURE = "GET_GOOGLE_REVIEW_FAILURE";