export const GET_HEADER_MENU_REQUEST = "GET_HEADER_MENU_REQUEST";
export const GET_HEADER_MENU_SUCCUSS = "GET_HEADER_MENU_SUCCUSS";
export const GET_HEADER_MENU_FAILURE = "GET_HEADER_MENU_FAILURE";
export const GET_FOOTER_MENU_REQUEST = "GET_FOOTER_MENU_REQUEST";
export const GET_FOOTER_MENU_SUCCUSS = "GET_FOOTER_MENU_SUCCUSS";
export const GET_FOOTER_MENU_FAILURE = "GET_FOOTER_MENU_FAILURE";