export const GET_RENTAL_VEHICLE_REQUEST = "GET_RENTAL_VEHICLE_REQUEST";
export const GET_RENTAL_VEHICLE_SUCCESS = "GET_RENTAL_VEHICLE_SUCCESS";
export const GET_RENTAL_VEHICLE_FAILURE = "GET_RENTAL_VEHICLE_FAILURE";