export const GET_SECTION_HEADER_REQUEST = "GET_SECTION_HEADER_REQUEST";
export const GET_SECTION_HEADER_SUCCESS = "GET_SECTION_HEADER_SUCCESS";
export const GET_SECTION_HEADER_FAILURE = "GET_SECTION_HEADER_FAILURE";