export const GET_TOP_SIGHT_SEEING_REQUEST = "GET_TOP_SIGHT_SEEING_REQUEST";
export const GET_TOP_SIGHT_SEEING_SUCCESS = "GET_TOP_SIGHT_SEEING_SUCCESS";
export const GET_TOP_SIGHT_SEEING_FAILURE = "GET_TOP_SIGHT_SEEING_FAILURE";