name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main  # You can change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust to the version you want

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Deploy to Hostinger using SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          privateKey: ${{ secrets.PRIVATE_KEY}}
          script: |
            cd /path/to/your/project/SweetTrip
            git pull origin main  # Pull latest code from GitHub
            npm install  # Install dependencies
            npm run build  # Build the application
            pm2 restart nextjs-app  # Restart the app using PM2 (adjust if using other tools)
